# This is a basic workflow to help you get started with Actions

name: Android Build CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  android:
    name: buildAndroid
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [release, debug]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        
      - name: Install System Dependencies
        run: | 
         sudo apt-get update
         sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev libmbedtls-dev libpng-dev libturbojpeg-dev libuv1-dev libvorbis-dev
        
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: '19'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.4
          
      - name: Install haxelib stuff
        run: |
          haxelib --quiet install lime 7.9.0
          haxelib --quiet install openfl 9.1.0
          haxelib --quiet install flixel 4.11.0
          haxelib --quiet install lime-samples
          haxelib --quiet install hscript
          haxelib --quiet install flixel-ui
          haxelib --quiet install flixel-addons
          haxelib --quiet install flxanimate 1.2.0
          haxelib --quiet git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib --quiet git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git
          haxelib -quiet git extension-webview https://github.com/Aly-Ant0/extension-webview.git
          haxelib --quiet git linc_luajit https://github.com/AndreiRudenko/linc_luajit.git
          haxelib list

      - name: Config Lime stuff
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set flixel 4.11.0
          haxelib set lime 7.9.0
          haxelib set openfl 9.1.0
          haxelib set flxanimate 1.2.0
          haxelib list
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile APK
        run: haxelib run lime build android -${{ matrix.arch }}

      - name: finally the apk
        uses: actions/upload-artifact@main
        with:
          name: Hotline Medley Update-${{ matrix.arch }}
          path: export/${{ matrix.arch }}/android/bin/app/build/outputs/apk/debug
          if-no-files-found: error
